services:
  server:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile.server
      args:
        APP_PATH: servers/server
        APP_NAME: server
        DB_HOST: mariadb
        APP_PORT: 8080
    image: server-app-compose
    container_name: server-app
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - my-network
    depends_on:
      - mariadb
  buildings:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile
      args:
        APP_PATH: apps/buildings
        VITE_API_URL: http://192.168.40.100:8080
    image: buildings-app-compose
    container_name: buildings-app
    restart: unless-stopped
    ports:
      - '8082:80'
    depends_on:
      - server
    networks:
      - my-network

  mariadb:
    image: mariadb:latest
    container_name: prizm-mariadb
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: prizm
    # volumes:
    #   - mariadb-data:/var/lib/mysql
    #   - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db-init/init_USER.sql:/docker-entrypoint-initdb.d/init_USER.sql
      - ./db-init/init_LMS.sql:/docker-entrypoint-initdb.d/init_LMS.sql  
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mariadb-data:
