services:
  server:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile.server
      args:
        APP_PATH: _servers/server
        APP_NAME: server
        DB_HOST: mariadb
        APP_PORT: 8080
    image: server-app-compose
    container_name: server-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - my-network
    depends_on:
      - mariadb
    volumes:
      - ./data:/app/public
      - ../../tileMaps:/app/tileMaps
      # Docker 바인드 마운트 : 복사 개념이 아니라 공유하는 개념
      # 로컬 폴더에 컨테이너의 위치를 연결하여, 컨테이너가 해당 위치를 참조, 양방향 실시간 동기화 형성

  buildings:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile
      args:
        APP_PATH: _apps/buildings
        VITE_API_URL: http://192.168.40.82:8080
    image: buildings-app-compose
    container_name: buildings-app
    restart: unless-stopped
    ports:
      - "8082:80"
    depends_on:
      - server
    networks:
      - my-network

  mariadb:
    image: mariadb:latest
    container_name: prizm-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: prizm
    volumes:
      - mariadb-data:/var/lib/mysql
      # ordering : alphabet - schema first, then data
      - ./db-init/init1.1-user-schema.sql:/docker-entrypoint-initdb.d/init1.1-user-schema.sql
      - ./db-init/init1.2-user-data.sql:/docker-entrypoint-initdb.d/init1.2-user-data.sql
      - ./db-init/init2.1-nms-schema.sql:/docker-entrypoint-initdb.d/init2.1-nms-schema.sql
      - ./db-init/init2.2-nms-data.sql:/docker-entrypoint-initdb.d/init2.2-nms-data.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mariadb-data:
