CREATE DATABASE IF NOT EXISTS prizm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE prizm;

-- 사용자 (USER_TN_USERS)
CREATE TABLE IF NOT EXISTS `USER_TN_USERS` (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 nickname VARCHAR(50),
 password VARCHAR(255) NOT NULL,
 user_type ENUM('ADMIN_MAIN', 'ADMIN_SUB', 'USER') NOT NULL DEFAULT 'USER',
 email VARCHAR(100) NOT NULL UNIQUE,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 역할 (USER_TC_ROLES)
CREATE TABLE IF NOT EXISTS `USER_TC_ROLES` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role_code VARCHAR(50) NOT NULL UNIQUE, -- ADMIN_MAIN, ADMIN_SUB, USER
  role_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 사용자-역할 매핑 (USER_TN_USER_ROLES)
CREATE TABLE IF NOT EXISTS `USER_TN_USER_ROLES` (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY(user_id, role_id),
  FOREIGN KEY(user_id) REFERENCES USER_TN_USERS(id) ON DELETE CASCADE,
  FOREIGN KEY(role_id) REFERENCES USER_TC_ROLES(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 메뉴 (USER_TC_MENUS)
CREATE TABLE IF NOT EXISTS `USER_TC_MENUS` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(50) NOT NULL,
  path VARCHAR(100) NOT NULL UNIQUE,
  icon_name VARCHAR(50), -- lucide-react icon name
  parent_id BIGINT,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY(parent_id) REFERENCES USER_TC_MENUS(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 역할-메뉴 권한 (USER_TN_ROLE_MENU_PERMISSIONS)
CREATE TABLE IF NOT EXISTS `USER_TN_ROLE_MENU_PERMISSIONS` (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  can_access BOOLEAN DEFAULT FALSE,
  PRIMARY KEY(role_id, menu_id),
  FOREIGN KEY(role_id) REFERENCES USER_TC_ROLES(id) ON DELETE CASCADE,
  FOREIGN KEY(menu_id) REFERENCES USER_TC_MENUS(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;